### PR TITLE
Fix for regression from CVE fix in PR #660

### PR DESCRIPTION
**Pull request by ashoke-cube**
## Problem
Excluding `hadoop-shaded-guava` for CVE fix in commit https://github.com/confluentinc/kafka-connect-storage-cloud/commit/8a80a19363f5c8d89d7b52367352a25b1ff1de8b
resulted in a regression with `NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/collect/Interners`
while using the `io.confluent.connect.s3.format.parquet.ParquetFormat` for `format.class` field in config.

## Solution
[kafka-connect-storage-common](https://github.com/confluentinc/kafka-connect-storage-common/tree/master) has an updated hadoop-shaded-guava without the CVE.

##### Does this solution apply anywhere else?
- [ ] yes
- [x] no

##### Testing done:
- [x] Unit tests
- [x] Integration tests
- [ ] System tests
- [x] Manual tests

### CODE REVIEW

**Review by pbadani — APPROVED** [review]
LGTM after testing with parquet input format in docker playground.
